- hosts: namespace_workloads
  become: true  # Run tasks with root privileges
  tasks:
    - name: Ensure python3-libdnf5 is installed
      ansible.builtin.package:
        name: python3-libdnf5
        state: present
    - name: Install httpd package
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes  
